import type { AgentApiResponse, AgentArtifactBundle, ActionPlanResult } from "./agentTypes";
import type { SignalApi } from "./types";
import { getApiBase } from "./client";
import { AgentServiceError, formatAgentFetchError } from "../utils/agentErrors";

function agentsBaseUrl(base: string): string {
  const trimmed = base.replace(/\/$/, "");
  return `${trimmed}/api/v1/agents`;
}

function assertLiveArtifacts(bundle: AgentArtifactBundle): void {
  if (bundle.degradedAgents?.length) {
    throw new AgentServiceError(
      `Live agents unavailable: ${bundle.degradedAgents.join(", ")}`,
    );
  }
  if (
    bundle.triage?.degradedMode ||
    bundle.analysis?.degradedMode ||
    bundle.actionPlan?.degradedMode
  ) {
    throw new AgentServiceError("Server returned rule-based output; Gemini agents are required.");
  }
}

function assertLiveActionPlan(plan: ActionPlanResult): void {
  if (plan.degradedMode) {
    throw new AgentServiceError("Action plan was not generated by Gemini (degraded mode disabled).");
  }
}

const AGENT_FETCH_MS = 120_000;

async function agentPost<T>(path: string, body: unknown): Promise<T> {
  const base = await getApiBase();
  const url = `${agentsBaseUrl(base)}${path}`;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), AGENT_FETCH_MS);
  let res: Response;
  try {
    res = await fetch(url, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(body),
      signal: controller.signal,
    });
  } catch (e) {
    const msg = (e as Error).name === "AbortError" ? "Agent request timed out (120s)" : (e as Error).message;
    throw formatAgentFetchError(msg ?? String(e), base);
  } finally {
    clearTimeout(timer);
  }

  let json: AgentApiResponse<T>;
  try {
    json = (await res.json()) as AgentApiResponse<T>;
  } catch {
    throw formatAgentFetchError(`Invalid response (HTTP ${res.status})`, base);
  }

  if (!res.ok || !json.success || json.data == null) {
    throw formatAgentFetchError(json.error ?? `HTTP ${res.status}`, base);
  }

  return json.data;
}

/** Alert analysis: triage + dossier only (faster — action plan loads on its screen). */
export async function enrichAlertWithAgents(signal: SignalApi): Promise<AgentArtifactBundle> {
  const data = await agentPost<AgentArtifactBundle>(
    `/alerts/${encodeURIComponent(signal.id)}/enrich?steps=triage,analysis`,
    { signal },
  );
  if (!data.triage || !data.analysis) {
    throw new AgentServiceError("Incomplete agent response (triage or analysis missing).");
  }
  assertLiveArtifacts(data);
  return data;
}

export async function fetchActionPlanForSignal(signal: SignalApi): Promise<ActionPlanResult> {
  const crisisId = `pk-${signal.id}`;
  const data = await agentPost<ActionPlanResult>(
    `/crises/${encodeURIComponent(crisisId)}/action-plan`,
    { signal },
  );
  assertLiveActionPlan(data);
  return data;
}

export async function enrichCrisisWithAgents(
  crisisId: string,
  signal?: SignalApi,
): Promise<AgentArtifactBundle> {
  const data = await agentPost<AgentArtifactBundle>(
    `/crises/${encodeURIComponent(crisisId)}/enrich`,
    signal ? { signal } : {},
  );
  assertLiveArtifacts(data);
  return data;
}
