/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RobustnessRouteImport } from './routes/robustness'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as CrisesRouteImport } from './routes/crises'
import { Route as CoordinationRouteImport } from './routes/coordination'
import { Route as AegisRouteImport } from './routes/aegis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrisesIdRouteImport } from './routes/crises.$id'

const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RobustnessRoute = RobustnessRouteImport.update({
  id: '/robustness',
  path: '/robustness',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisesRoute = CrisesRouteImport.update({
  id: '/crises',
  path: '/crises',
  getParentRoute: () => rootRouteImport,
} as any)
const CoordinationRoute = CoordinationRouteImport.update({
  id: '/coordination',
  path: '/coordination',
  getParentRoute: () => rootRouteImport,
} as any)
const AegisRoute = AegisRouteImport.update({
  id: '/aegis',
  path: '/aegis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrisesIdRoute = CrisesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrisesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aegis': typeof AegisRoute
  '/coordination': typeof CoordinationRoute
  '/crises': typeof CrisesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/recovery': typeof RecoveryRoute
  '/resources': typeof ResourcesRoute
  '/robustness': typeof RobustnessRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/simulation': typeof SimulationRoute
  '/crises/$id': typeof CrisesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aegis': typeof AegisRoute
  '/coordination': typeof CoordinationRoute
  '/crises': typeof CrisesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/recovery': typeof RecoveryRoute
  '/resources': typeof ResourcesRoute
  '/robustness': typeof RobustnessRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/simulation': typeof SimulationRoute
  '/crises/$id': typeof CrisesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aegis': typeof AegisRoute
  '/coordination': typeof CoordinationRoute
  '/crises': typeof CrisesRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/recovery': typeof RecoveryRoute
  '/resources': typeof ResourcesRoute
  '/robustness': typeof RobustnessRoute
  '/settings': typeof SettingsRoute
  '/signals': typeof SignalsRoute
  '/simulation': typeof SimulationRoute
  '/crises/$id': typeof CrisesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aegis'
    | '/coordination'
    | '/crises'
    | '/notifications'
    | '/recovery'
    | '/resources'
    | '/robustness'
    | '/settings'
    | '/signals'
    | '/simulation'
    | '/crises/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aegis'
    | '/coordination'
    | '/crises'
    | '/notifications'
    | '/recovery'
    | '/resources'
    | '/robustness'
    | '/settings'
    | '/signals'
    | '/simulation'
    | '/crises/$id'
  id:
    | '__root__'
    | '/'
    | '/aegis'
    | '/coordination'
    | '/crises'
    | '/notifications'
    | '/recovery'
    | '/resources'
    | '/robustness'
    | '/settings'
    | '/signals'
    | '/simulation'
    | '/crises/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AegisRoute: typeof AegisRoute
  CoordinationRoute: typeof CoordinationRoute
  CrisesRoute: typeof CrisesRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  RecoveryRoute: typeof RecoveryRoute
  ResourcesRoute: typeof ResourcesRoute
  RobustnessRoute: typeof RobustnessRoute
  SettingsRoute: typeof SettingsRoute
  SignalsRoute: typeof SignalsRoute
  SimulationRoute: typeof SimulationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robustness': {
      id: '/robustness'
      path: '/robustness'
      fullPath: '/robustness'
      preLoaderRoute: typeof RobustnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crises': {
      id: '/crises'
      path: '/crises'
      fullPath: '/crises'
      preLoaderRoute: typeof CrisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coordination': {
      id: '/coordination'
      path: '/coordination'
      fullPath: '/coordination'
      preLoaderRoute: typeof CoordinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aegis': {
      id: '/aegis'
      path: '/aegis'
      fullPath: '/aegis'
      preLoaderRoute: typeof AegisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crises/$id': {
      id: '/crises/$id'
      path: '/$id'
      fullPath: '/crises/$id'
      preLoaderRoute: typeof CrisesIdRouteImport
      parentRoute: typeof CrisesRoute
    }
  }
}

interface CrisesRouteChildren {
  CrisesIdRoute: typeof CrisesIdRoute
}

const CrisesRouteChildren: CrisesRouteChildren = {
  CrisesIdRoute: CrisesIdRoute,
}

const CrisesRouteWithChildren =
  CrisesRoute._addFileChildren(CrisesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AegisRoute: AegisRoute,
  CoordinationRoute: CoordinationRoute,
  CrisesRoute: CrisesRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  RecoveryRoute: RecoveryRoute,
  ResourcesRoute: ResourcesRoute,
  RobustnessRoute: RobustnessRoute,
  SettingsRoute: SettingsRoute,
  SignalsRoute: SignalsRoute,
  SimulationRoute: SimulationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
