import type { ResourceUnit } from "./types";

/** Operational pools — Islamabad / Rawalpindi (aligned with backend mock_data). */
export const CURATED_UNITS: ResourceUnit[] = [
  {
    resource_id: "isb_rescue_1122_alpha",
    name: "Rescue 1122 — Islamabad sector dispatch",
    kind: "rescue_water",
    agency: "Rescue 1122 Punjab",
    quantity_available: 12,
    quantity_total: 16,
    lat: 33.6844,
    lon: 73.0479,
    tags: ["flood", "accident", "fire", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_flood_task_alpha",
    name: "Islamabad flood / swift-water task force",
    kind: "rescue_water",
    agency: "CDA Emergency",
    quantity_available: 14,
    quantity_total: 18,
    lat: 33.721,
    lon: 73.043,
    tags: ["flood", "infrastructure", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_traffic_cell",
    name: "ICT Police — traffic & corridor control",
    kind: "security",
    agency: "ICT Police",
    quantity_available: 40,
    quantity_total: 48,
    lat: 33.6935,
    lon: 73.0652,
    tags: ["flood", "accident", "civil_unrest", "infrastructure", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_police_ops",
    name: "ICT Police — operations & public order cell",
    kind: "security",
    agency: "ICT Police",
    quantity_available: 24,
    quantity_total: 32,
    lat: 33.707,
    lon: 73.055,
    tags: ["civil_unrest", "accident", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_ems_central",
    name: "PIMS-linked EMS staging — district central",
    kind: "medical",
    agency: "PIMS / Rescue 1122",
    quantity_available: 18,
    quantity_total: 22,
    lat: 33.7069,
    lon: 73.0557,
    tags: ["flood", "fire", "heatwave", "accident", "earthquake", "disease_outbreak", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_edhi_dispatch",
    name: "EDHI ambulance dispatch — Islamabad",
    kind: "medical",
    agency: "EDHI Foundation",
    quantity_available: 10,
    quantity_total: 14,
    lat: 33.652,
    lon: 73.04,
    tags: ["accident", "heatwave", "flood", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_poly_clinic_ems",
    name: "Poly Clinic emergency receiving",
    kind: "medical",
    agency: "Poly Clinic",
    quantity_available: 8,
    quantity_total: 12,
    lat: 33.693,
    lon: 73.038,
    tags: ["heatwave", "disease_outbreak", "accident", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_cda_fire",
    name: "CDA fire & rescue station — central",
    kind: "fire",
    agency: "CDA Fire",
    quantity_available: 6,
    quantity_total: 8,
    lat: 33.69,
    lon: 73.05,
    tags: ["fire", "accident", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_cooling_center",
    name: "DWO cooling / shade shelters + ORS",
    kind: "shelter",
    agency: "District Welfare",
    quantity_available: 800,
    quantity_total: 1200,
    lat: 33.658,
    lon: 73.01,
    tags: ["heatwave", "flood", "power_outage", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_water_utilitycrew",
    name: "CDA bulk-water & mains repair",
    kind: "utility",
    agency: "WASA / CDA",
    quantity_available: 10,
    quantity_total: 14,
    lat: 33.684,
    lon: 73.032,
    tags: ["infrastructure", "flood", "power_outage", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_mobile_gens_alpha",
    name: "Mobile generator & line truck platoon",
    kind: "power_mobile",
    agency: "IESCO field ops",
    quantity_available: 20,
    quantity_total: 24,
    lat: 33.688,
    lon: 73.038,
    tags: ["power_outage", "heatwave", "infrastructure", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_pepa_aq",
    name: "PEPA air-quality response unit",
    kind: "ngo",
    agency: "PEPA",
    quantity_available: 4,
    quantity_total: 6,
    lat: 33.71,
    lon: 73.06,
    tags: ["disease_outbreak", "heatwave", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "isb_mask_ngo",
    name: "N95 mask distribution NGOs — twin cities",
    kind: "ngo",
    agency: "NGO coalition",
    quantity_available: 6,
    quantity_total: 10,
    lat: 33.675,
    lon: 73.02,
    tags: ["heatwave", "all"],
    min_tier: 1,
    source: "curated",
  },
  {
    resource_id: "ndma_uas_cell",
    name: "NDMA reconnaissance UAS cell",
    kind: "drone",
    agency: "NDMA",
    quantity_available: 6,
    quantity_total: 8,
    lat: 33.701,
    lon: 73.052,
    tags: ["flood", "earthquake", "accident", "all"],
    min_tier: 1,
    source: "curated",
  },
];
